**INFORMACION EXTRA: TENIAMOS CLARO DESDE EL PRINCIPIO QUE DEBIAMOS HACER**
Rellenar una matriz numpy vacia de tamaño 365,740 con una lista en cada celda DE 24 REGISTROS extraidos de la matriz data:
np.random.seed(2023)
data = np.random.randint(low=12,high=150,size=(999000,16))

pero teniendo en cuenta que los 24 registros que estaran dentro de cada celda no están en la misma fila de la matriz inicial, si no que estaran formados por, para el primer vecino, la primera fila y media de la segunda de la matriz data; las del siguiente vecino, la media segunda fila que falta y la tercera entera; para el tercer vecino, la 4º fila de data y la mitad de la quinta de data... y asi para todos los vecinos en todos los dias

PARA EL PROBLEMA PRINCIPAL, QUE ERA NO PODER SELECCIONAR LA PRIMERA FILA DE DATA PARA EL PRIMER VECINO, LA SEGUNDA PARA EL SEGUNDO QUE ERA LA FORMA FACIL, lo hemos solucionado asi:
- Hemos creado un TRIPLE BUCLE, primer bucle recorre filas, segundo columnas y el tercero LOS REGISTROS QUE NECESITAMOS(24) que localizamos a traves de INDICES, y realizamos las operaciones necesarias para que los índices se actualicen correctamente para cada cliente (sumamos a indice de inicio los 24 registros para cada nuevo cliente, tenemos en cuenta el tamaño de la matriz para hacer que la selección sea cíclica (cuando termine fila, que pase a la siguiente) y transformamos los índices planos en bidimensionales.) Los 24 registros de cada cliente Y EN CADA CELDA se almacenan en una lista vacía llamada DATOS_CLIENTE y posteriormente la transformamos en matriz numpy y la almacenamos en la celda de la matriz resultante.

In [10]:
import numpy as np

# Generar la matriz de datos original
np.random.seed(2023)
data = np.random.randint(low=12, high=150, size=(999000, 16))

# Dimensiones de la matriz resultante
filas_resultado, columnas_resultado = 365, 740

# Número de registros por cliente
registros_por_cliente = 24

# Crear la matriz EN LA QUE SE INCLUIRAN LOS DATOS DE LA ORIGINAL,POR CELDAS
matriz_resultado = np.empty((filas_resultado, columnas_resultado), dtype=object) # la creamos vacía para rellenarla luego

# Índice de inicio en la matriz de datos
indice_inicio = 0

# Bucle para recorrer las filas
for i in range(filas_resultado):
    # Bucle para recorrer las columnas
    for j in range(columnas_resultado):
        # Bucle para seleccionar los 24 registros consecutivos (EL MAS IMPORTANTE)
        datos_cliente = [] # LISTA VACIA PARA INTRODUCIR LOS DATOS QUE SE REQUIERE
        for k in range(registros_por_cliente):
            # Calcular el índice actual teniendo en cuenta el final de cada fila
            indice_actual = (indice_inicio + k) % data.size #  Si el índice calculado supera el tamaño total de la matriz, el operador % 
            # permite la seleccion cíclica de los registros.

            # Obtener la fila y la columna correspondientes(para convertir un índice plano (indice_actual) 
            # en un par de índices bidimensionales (fila_actual y columna_actual))
            fila_actual = indice_actual // data.shape[1]
            columna_actual = indice_actual % data.shape[1]

            # Agregar el dato actual a la lista
            datos_cliente.append(data[fila_actual, columna_actual])

        # Almacenar los datos en la celda correspondiente de la matriz resultante
        matriz_resultado[i, j] = np.array(datos_cliente)

        # Actualizar el índice de inicio para el siguiente cliente
        indice_inicio += registros_por_cliente

# La matriz_resultante ahora contiene los conjuntos de registros necesarios para cada cliente.
print(matriz_resultado)
print(matriz_resultado.shape)



[[array([ 99,  37,  15, 128,  64, 113,  34,  89,  51, 143,  70,  40, 122,
          75,  41,  61, 126, 124,  61,  65,  27, 123, 139, 100])
  array([ 84,  77,  34, 147,  37,  46,  61,  89, 127, 127,  99,  46, 116,
         141,  81, 120,  63,  31,  81,  43, 133, 145,  19,  95])
  array([ 67, 137,  18, 131,  40,  58,  90,  49,  75,  48, 145, 105,  78,
          70,  84,  98,  66, 112,  64, 101,  79,  83,  83,  48])
  ...
  array([ 88,  56,  40, 101,  53,  57,  86, 144, 134, 121, 116,  37,  82,
          92,  72, 121, 102,  85,  30, 144, 146, 120, 140,  38])
  array([144,  80,  79,  89,  29, 144,  72,  83, 104,  44,  46,  53,  31,
          60,  33,  35,  85, 115, 135,  51, 149, 133,  94,  40])
  array([ 65,  56,  92, 125, 125, 123, 122, 107, 118,  69,  74,  38,  12,
          74,  96,  73,  33,  94,  96,  27, 142,  13,  32,  15])         ]
 [array([ 97, 103, 113,  82, 112, 114,  35,  50,  94,  47, 109,  38,  65,
          46,  37,  80, 135,  12,  95, 103,  65,  65,  67,  75])
  array([14

In [ ]:
# otra forma, CON RESHAPE(-1,740,24), -1 ES PARA VER TODOS LOS QUE QUEPAN EN LA PRIMERA DIMENSION
# MUCHO MAS FACIL.


In [12]:
# Ahora, vamos a buscar la media de los arrays de cada celda:

# Crear una matriz para almacenar las medias 
medias_por_celda = np.empty_like(matriz_resultado, dtype=float) # mejor que np.zeros, porque vamos a sobreescribir los valores.

# Bucle para recorrer las filas
for i in range(filas_resultado):
    # Bucle para recorrer las columnas
    for j in range(columnas_resultado):
        # Calcular la media de los datos en la celda actual
        media_celda = np.mean(matriz_resultado[i, j])

        # Almacenar la media en la matriz de medias por celda
        medias_por_celda[i, j] = media_celda

# Ahora, medias_por_celda contiene las medias de cada array en cada celda de la matriz resultante
print(medias_por_celda)

[[81.125      85.08333333 80.375      ... 91.875      80.33333333
  75.875     ]
 [76.625      77.45833333 77.75       ... 89.54166667 71.25
  60.41666667]
 [74.375      82.95833333 77.125      ... 88.83333333 87.04166667
  84.04166667]
 ...
 [73.625      85.33333333 80.875      ... 80.70833333 77.08333333
  80.5       ]
 [89.04166667 89.95833333 82.79166667 ... 83.75       72.04166667
  71.        ]
 [92.375      80.125      84.75       ... 95.25       77.08333333
  82.625     ]]


In [ ]:
# OTRA OPCION, CON UNA FUNCION!! COMO BEA, DEF CONSUMO_MEDIO(DATOS CON ARGUMENTOS, LA FUNCION NUMPY Y RETURN)

In [34]:
# Y AHORA, EL COSTE TOTAL POR DIA
# Costo por kilovatio
costo_por_kw = 0.25

# Crear una matriz para almacenar los costos totales de cada celda
costos_totales_por_celda = np.empty_like(matriz_resultado, dtype=float)

# Bucle para recorrer las filas
for i in range(filas_resultado):
    # Bucle para recorrer las columnas
    for j in range(columnas_resultado):
        # Sumar todos los valores en la celda y multiplicar por el costo por kilovatio
        costos_totales_por_celda[i, j] = np.sum(matriz_resultado[i, j]) * costo_por_kw

# Ahora, costos_totales_por_celda contiene los costos totales de cada celda en la matriz resultante
print(costos_totales_por_celda)

[[486.75 510.5  482.25 ... 551.25 482.   455.25]
 [459.75 464.75 466.5  ... 537.25 427.5  362.5 ]
 [446.25 497.75 462.75 ... 533.   522.25 504.25]
 ...
 [441.75 512.   485.25 ... 484.25 462.5  483.  ]
 [534.25 539.75 496.75 ... 502.5  432.25 426.  ]
 [554.25 480.75 508.5  ... 571.5  462.5  495.75]]
